In [1]:
#Module 2 :  Data Preprocessing
# Machine Learning Course

In [2]:
#  importing ther library
import numpy             as np                      # Mathmatical tools
import matplotlib.pyplot as plt         
import pandas            as pd

In [4]:
# Import the dataset
dataset  = pd.read_csv('Data.csv')


In [5]:
dataset

Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes
5   France  35.0  58000.0       Yes
6    Spain   NaN  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes

In [65]:
X = dataset.iloc[:,:-1].values

In [66]:
X

array([['France', 44.0, 72000.0],
       ['Spain', 27.0, 48000.0],
       ['Germany', 30.0, 54000.0],
       ['Spain', 38.0, 61000.0],
       ['Germany', 40.0, nan],
       ['France', 35.0, 58000.0],
       ['Spain', nan, 52000.0],
       ['France', 48.0, 79000.0],
       ['Germany', 50.0, 83000.0],
       ['France', 37.0, 67000.0]], dtype=object)

In [67]:
Y = dataset.iloc[:,-1].values

In [68]:
Y

array(['No', 'Yes', 'No', 'No', 'Yes', 'Yes', 'No', 'Yes', 'No', 'Yes'], dtype=object)

In [69]:
# Taking care of Missing Data

In [70]:
'''
we have two missing data cell
 possiable actions  
   1- mean the row
   2- get the mean
'''

from sklearn.preprocessing  import Imputer

'''
missing_values : the va;ue which will be consider as a missing  (Nan) , can be any other data value 0 ,-1,44 
Strategy : mean . median, most_frequent
# axis = 0 ( mean of the column ) , 1 mean of the rows
'''
mka_imputer = Imputer(missing_values='NaN', strategy = 'mean' , axis = 0)   

In [71]:
mka_imputer = mka_imputer.fit(X[:,1:3])

In [72]:
X[:,1:3]=mka_imputer.transform(X[:,1:3])

In [73]:
X

array([['France', 44.0, 72000.0],
       ['Spain', 27.0, 48000.0],
       ['Germany', 30.0, 54000.0],
       ['Spain', 38.0, 61000.0],
       ['Germany', 40.0, 63777.77777777778],
       ['France', 35.0, 58000.0],
       ['Spain', 38.77777777777778, 52000.0],
       ['France', 48.0, 79000.0],
       ['Germany', 50.0, 83000.0],
       ['France', 37.0, 67000.0]], dtype=object)

# Deal with Categoricla variable


In [93]:
# convert / encode categoical variable form charachter to number in order to be used in the equations
from sklearn.preprocessing  import LabelEncoder,OneHotEncoder


In [75]:
mka_labelencoder_X = LabelEncoder()

In [88]:
X[:,0]=  mka_labelencoder_X.fit_transform(X[:,0])

In [89]:
X

array([[0L, 44.0, 72000.0],
       [2L, 27.0, 48000.0],
       [1L, 30.0, 54000.0],
       [2L, 38.0, 61000.0],
       [1L, 40.0, 63777.77777777778],
       [0L, 35.0, 58000.0],
       [2L, 38.77777777777778, 52000.0],
       [0L, 48.0, 79000.0],
       [1L, 50.0, 83000.0],
       [0L, 37.0, 67000.0]], dtype=object)

In [91]:
# ML module base on equation  so 0 > 1 > 2  for here ML will consider France < Spian < Germany which is not the case as these 
# variable are categorical.

# the solution is to use the dummy variables

In [95]:
mka_onehotencoder = OneHotEncoder(categorical_features= [0])
# Categorical_feature

In [96]:
X = mka_onehotencoder.fit_transform(X).toarray()

In [97]:
X

array([[  1.00000000e+00,   0.00000000e+00,   0.00000000e+00,
          4.40000000e+01,   7.20000000e+04],
       [  0.00000000e+00,   0.00000000e+00,   1.00000000e+00,
          2.70000000e+01,   4.80000000e+04],
       [  0.00000000e+00,   1.00000000e+00,   0.00000000e+00,
          3.00000000e+01,   5.40000000e+04],
       [  0.00000000e+00,   0.00000000e+00,   1.00000000e+00,
          3.80000000e+01,   6.10000000e+04],
       [  0.00000000e+00,   1.00000000e+00,   0.00000000e+00,
          4.00000000e+01,   6.37777778e+04],
       [  1.00000000e+00,   0.00000000e+00,   0.00000000e+00,
          3.50000000e+01,   5.80000000e+04],
       [  0.00000000e+00,   0.00000000e+00,   1.00000000e+00,
          3.87777778e+01,   5.20000000e+04],
       [  1.00000000e+00,   0.00000000e+00,   0.00000000e+00,
          4.80000000e+01,   7.90000000e+04],
       [  0.00000000e+00,   1.00000000e+00,   0.00000000e+00,
          5.00000000e+01,   8.30000000e+04],
       [  1.00000000e+00,   0.0000000

In [98]:
#Note  : One Hot Encoding can also be done using : DictVectorizer
   
measurements = [
     {'city': 'Dubai', 'temperature': 33.},
     {'city': 'London', 'temperature': 12.},
     {'city': 'San Fransisco', 'temperature': 18.},
 ]

from sklearn.feature_extraction import DictVectorizer

vec = DictVectorizer()

In [99]:


vec.fit_transform(measurements).toarray()



array([[  1.,   0.,   0.,  33.],
       [  0.,   1.,   0.,  12.],
       [  0.,   0.,   1.,  18.]])

In [100]:
vec.get_feature_names()

['city=Dubai', 'city=London', 'city=San Fransisco', 'temperature']

In [103]:
# convert y from yes and no to 0 and 1
mka_labelencoder_y = LabelEncoder()
Y=  mka_labelencoder_y.fit_transform(Y)

In [104]:
Y

array([0, 1, 0, 0, 1, 1, 0, 1, 0, 1], dtype=int64)

In [105]:
# Splitting the data to train and test

In [107]:
from sklearn.cross_validation import train_test_split

In [108]:
X_train, X_test,Y_train, Y_test =  train_test_split(X,Y,test_size=0.2,random_state=0)

In [109]:
X_train

array([[  0.00000000e+00,   1.00000000e+00,   0.00000000e+00,
          4.00000000e+01,   6.37777778e+04],
       [  1.00000000e+00,   0.00000000e+00,   0.00000000e+00,
          3.70000000e+01,   6.70000000e+04],
       [  0.00000000e+00,   0.00000000e+00,   1.00000000e+00,
          2.70000000e+01,   4.80000000e+04],
       [  0.00000000e+00,   0.00000000e+00,   1.00000000e+00,
          3.87777778e+01,   5.20000000e+04],
       [  1.00000000e+00,   0.00000000e+00,   0.00000000e+00,
          4.80000000e+01,   7.90000000e+04],
       [  0.00000000e+00,   0.00000000e+00,   1.00000000e+00,
          3.80000000e+01,   6.10000000e+04],
       [  1.00000000e+00,   0.00000000e+00,   0.00000000e+00,
          4.40000000e+01,   7.20000000e+04],
       [  1.00000000e+00,   0.00000000e+00,   0.00000000e+00,
          3.50000000e+01,   5.80000000e+04]])

In [110]:
X_test

array([[  0.00000000e+00,   1.00000000e+00,   0.00000000e+00,
          3.00000000e+01,   5.40000000e+04],
       [  0.00000000e+00,   1.00000000e+00,   0.00000000e+00,
          5.00000000e+01,   8.30000000e+04]])

In [111]:
Y_train

array([1, 1, 1, 0, 1, 0, 0, 1], dtype=int64)

In [112]:
Y_test

array([0, 0], dtype=int64)

In [113]:
# Feature scaling 
'''
put all feature on the same scale in order to have same equiliden distance
most of ML algorithm handle the feature scaling internally

two common ways
1- Standarisation

X_stand =  (x - mean(x)) / Standard deviation (x)

2- Normalisation 

X_norm  = ( x - min(X) )    /  (max(x) - min (x) )

'''

In [114]:
from  sklearn.preprocessing import StandardScaler

In [115]:
mka_sc_X  = StandardScaler()

In [116]:
X_train  = mka_sc_X.fit_transform(X_train)
X_test   = mka_sc_X.transform(X_test)

In [117]:
X_train

array([[-1.        ,  2.64575131, -0.77459667,  0.26306757,  0.12381479],
       [ 1.        , -0.37796447, -0.77459667, -0.25350148,  0.46175632],
       [-1.        , -0.37796447,  1.29099445, -1.97539832, -1.53093341],
       [-1.        , -0.37796447,  1.29099445,  0.05261351, -1.11141978],
       [ 1.        , -0.37796447, -0.77459667,  1.64058505,  1.7202972 ],
       [-1.        , -0.37796447,  1.29099445, -0.0813118 , -0.16751412],
       [ 1.        , -0.37796447, -0.77459667,  0.95182631,  0.98614835],
       [ 1.        , -0.37796447, -0.77459667, -0.59788085, -0.48214934]])

In [118]:
X_test

array([[-1.        ,  2.64575131, -0.77459667, -1.45882927, -0.90166297],
       [-1.        ,  2.64575131, -0.77459667,  1.98496442,  2.13981082]])

In [119]:
# Data Processing Template

In [ ]:
#  importing ther library
import numpy                    as np                      # Mathmatical tools
import matplotlib.pyplot        as plt         
import pandas                   as pd
from   sklearn.preprocessing    import StandardScaler
from   sklearn.cross_validation import train_test_split
from   sklearn.feature_extraction import DictVectorizer


# Import the dataset
dataset  = pd.read_csv('Data.csv')
X = dataset.iloc[:,:-1].values
Y = dataset.iloc[:,-1].values

# Splitting the data to train and test
X_train, X_test,Y_train, Y_test =  train_test_split(X,Y,test_size=0.2,random_state=0)

'''
# Feature scaling 
mka_sc_X  = StandardScaler()
X_train  = mka_sc_X.fit_transform(X_train)
X_test   = mka_sc_X.transform(X_test)
'''